name: learn-github-actions

on:
  pull_request:
    types: [closed, submitted]
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.EC2_IP  }}
            USER_NAME : ${{ secrets.EC2_USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            # Commands to run on the EC2 instance
            cd /home/ubuntu/
            rm -rf simple-java-maven-app
            git clone https://github.com/MorNetanel/simple-java-maven-app.git
            grep -m 1 -oP '<version>\K[^<]+' simple-java-maven-app/pom.xml > version
            VERSION=$(cat version)
            sudo docker run natimor/github_project:$VERSION
            "
            
          
