name: learn-github-actions

on:
  pull_request:
    types: [closed, submitted]
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.EC2PEM }}

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: <44.215.50.118>
          username: <ubuntu>
          key: ${{ secrets.PEM_FILE }}
          script: |
            # Run commands on the VM after connecting
            echo "Connected to VM"
            # Example command: list files in the home directory
            ls ~

