name: learn-github-actions

on:
  pull_request:
    types: [closed, submitted]
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.PEM_FILE }}
          
      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Connect to Remote VM
        run: |
          echo "$PEM_FILE" > remote.pem
          chmod 400 remote.pem
          ssh -i remote.pem ubuntu@44.215.50.118 "echo 'Connected to VM'; ls ~"
          

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: 44.215.50.118
          username: ubuntu
          key: ${{ secrets.PEM_FILE }}
          script: |
            # Run commands on the VM after connecting
            echo "Connected to VM"
            # Example command: list files in the home directory
            ls ~

