name: learn-github-actions

on:
  pull_request:
    types: [closed, submitted]
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          ssh -i secrets.EC2PEM ubuntu@44.215.50.118
          mkdir test1
