name: learn-github-actions

on:
  pull_request:
    types: [closed, submitted]
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: fetch jar
         uses: actions/checkout@v3
       - name: extract version
         run: echo "GITHUB_TAG=$(grep -m 1 -oP '<version>\K[^<]+' simple-java-maven-app/pom.xml)" >> $GITHUB_ENV
       
       - name: executing remote ssh commands using password
         uses: appleboy/ssh-action@v0.1.10
         with:
           host: ${{ secrets.EC2_IP }}
           username: ${{ secrets.EC2_USER_NAME }}
           key: ${{ secrets.AWS_PRIVATE_KEY }}
           script: |
             sudo apt update
             sudo docker rm $(sudo docker ps -aq)
             echo 1 ${{ env.GITHUB_TAG }}
             echo 2 "$GITHUB_TAG"
             sudo docker run -d ${{ secrets.DOCKERHUB_USERNAME }}/github_project:${{ env.GITHUB_TAG }}

            
          
